# -*- mode: org; -*-
#+AUTHOR: Hai NGUYEN
#+TITLE: [v0.2.1] clel - a Common Lisp library for scripting GNU Emacs

Status: mostly works, but:
- Slow to load roughly 30K of Elisp symbols into the system => 
- Choke on naked Elisp char reader macro (eg. "?\(") due to Lisp `read-lisp'
  function does not parse this Elisp expression correctly => needs modifying
  `read-lisp' function. Currently, there is a work-around: by wrapping that
  inside the "clel/1:#str[<...wrap into here...>]" syntax.

* Introduction

GNU Emacs has already been a Common Lisp IDE with the capability to run both in
the terminal and the GUI and a community and an ecosystem of packages.

This library seeks to expand its value further by letting its user:
- utilize Emacs to be a text-based user interface for Common Lisp applications
  when approriate (eg. as a UI for some sysadmin tasks since Emacs can run on
  both the Linux virtual terminal and the graphical desktop).
- (experimental,risky) configure Emacs in Common Lisp, with these advantages:
  - a package system and even package-local-nickname so that Emacs user no
    longer concern with package naming collision, now or in the future.
  - a standardized language
  - manage breaking changes in the API's of Emacs libraries thanks to the use of
    Lisp wrappers which abstract away the Elisp library API's.

* Dependencies

- SBCL (only tested on SBCL 2.0.11.debian on Debian Sid so far).
- GNU Emacs and Slime (only tested on Emacs 27.1 debian so far).
- quicklisp (optional, for easy installation of this library)
- sufficient RAM to run both Lisp images (might be in the ballpark of 350MB for
  an x86_64 machine ).

* Installation

This library is not in quicklisp.

To run, place this repository in your ~/quicklisp/local-projects/, then in the
Lisp REPL:

#+BEGIN_SRC lisp
   (progn (ql:register-local-projects)
          (ql:quickload 'clel)
#+END_SRC

and in Emacs-Slime/Sly:

#+BEGIN_SRC emacs-lisp
  (custom-set-variables
    '(slime-enable-evaluate-in-emacs t))
#+END_SRC

* Examples
:PROPERTIES:
:CUSTOM_ID: examples
:END:

Note: if you find a bug, please report it with the function
`clel-bug-report'. Thank you!

Please run the following for a trial *on a fresh Emacs instance* (otherwise you
will find your Emacs look and feel altered and have to restore your config via
re-loading your init-file):

(this example just load the  file file:example.lisp)


#+BEGIN_SRC emacs-lisp
  (slime-eval `(cl:progn
                 (ql:quickload 'clel)
                 ;; if not working, please change the code to load the
                 ;; "example.lisp" file of this repository:
                (cl:load ,(concat (file-name-directory (buffer-file-name))
                               "example.lisp")))
#+END_SRC

* Development

Emacs/Slime conversion of Common Lisp form to Elisp form have some gotchas,
due to:
- The conversion is through the Common Lisp reader, which omits the package
  prefix from the symbols of the current package, and all symbol's names are
  converted to UPCASE by default.
- Limited conversion capability of `swank::process-form-for-emacs' (which is
  used by `swank:eval-in-emacs' - the gateway for the Common Lisp image to send
  command to Emacs). For instance, in the code below:

#+BEGIN_SRC lisp
  (cl:eval '(list `(,2))) ; works fine
  (swank:eval-in-emacs '(list `(,2))) ; choked on ,2
#+END_SRC

** Other approaches not used

1. writing a compiler (in Elisp or Common Lisp) that transpile different versions
   of Elisp into one another (eg. transpiling from Elisp 25 to Elisp 26). This
   approach has a drawback: the user still use Elisp for their config instead of
   using Common Lisp.

* Other Solutions

- Sam Goldstein's elisp.lisp in CLOCC :: makes a Common Lisp interpreter for
  Elisp, while clel is just wrappers that call Elisp from Emacs.

* License

GPLv3
